# Generated by Django 5.2 on 2026-03-19 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100)),
                ('name_mm', models.CharField(max_length=100)),
                ('about', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_mm', models.CharField(max_length=200)),
                ('poem_mm', models.TextField()),
                ('poem_en', models.TextField()),
                ('about', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('featured', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(verbose_name='date added')),
                ('poet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poems.poet')),
            ],
        ),
    ]
