# Generated by Django 5.2 on 2026-03-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poet',
            name='source',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='poem',
            name='source',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
