# Generated by Django 5.2.9 on 2026-03-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_poet_source_alter_poem_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='poet',
            name='born_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of birth'),
        ),
        migrations.AddField(
            model_name='poet',
            name='dead_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of death'),
        ),
    ]
