# Generated by Django 5.2.9 on 2026-03-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_poet_born_year_poet_dead_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='born_year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Year of birth'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='dead_year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Year of death'),
        ),
    ]
